"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ShapeComponent = "Shape";
exports.ShapeComponent = ShapeComponent;
const ContainerComponent = "Container";
exports.ContainerComponent = ContainerComponent;
const TextComponent = "Text";
exports.TextComponent = TextComponent;
const BitmapComponent = "Bitmap";
exports.BitmapComponent = BitmapComponent;
