"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BitmapComponent = exports.TextComponent = exports.ContainerComponent = exports.ShapeComponent = void 0;
const ShapeComponent = "Shape";
exports.ShapeComponent = ShapeComponent;
const ContainerComponent = "Container";
exports.ContainerComponent = ContainerComponent;
const TextComponent = "Text";
exports.TextComponent = TextComponent;
const BitmapComponent = "Bitmap";
exports.BitmapComponent = BitmapComponent;
